moviebooking/moviebooking/urls.py
from django.contrib import admin
from django.urls import path,include,reverse_lazy
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('Accounts.urls')),
    path('',include('movies.urls')),
    path('booking/',include('bookings.urls')),
    path('tickets/',include('tickets.urls')),
    path('payment/',include('payments.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(
        settings.MEDIA_URL,document_root=settings.MEDIA_ROOT
    )

moviebooking/movies/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('',views.MovieList,name="movie_list"),
    path('movie/<int:id>',views.MovieDetail,name="movie_detail"),
    path('movie/shows',views.AvailableShows,name='available_shows'),
    path('movie/shows/<str:currentdate>',views.AvailableShows,name='available_shows_withDate'),
    path('movie/bookings',views.movie_bookings,name='see_bookings'),
]

moviebooking/payments/urls.py
from django.urls import path
from . import views
from . import webhooks
app_name='payment'
urlpatterns = [
    path('process/',views.payment_process,name='process'),
    path('completed/<int:booking_id>',views.payment_completed,name='completed'),
    path('failed/',views.payment_failed,name='failed'),
     path('webhook/',webhooks.stripe_webhook,name='stripe-webhook'),
     path('ticket/<int:booking_id>',views.payment_pdf,name='pdf_payment'),
     
   
    

]

moviebooking/payments/models.py
from django.db import models

# Create your models here.

moviebooking/payments/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from tickets.ticket import Ticket
from bookings.models import Booking
import redis
import stripe
from decimal import Decimal
from django.conf import settings
from django.http import HttpResponse
from .tasks import payment_completed_email
r=redis.Redis()


# Create your views here.
stripe.api_key=settings.STRIPE_SECRET_KEY
def payment_process(request):
   booking_id=request.session.get('booking_id')
   booked=Booking.objects.get(id=booking_id)
   print(booked.booking_items.all())
   if request.method == 'POST':
      success_url = request.build_absolute_uri(
            reverse('payment:completed',args=[booked.id])
        )
      cancel_url = request.build_absolute_uri(
            reverse('payment:failed')
        )
      session_data={
      'mode':'payment',
      'client_reference_id':booking_id,
      'success_url':success_url,
       'cancel_url':cancel_url,
       'line_items':[]
       }
      total_seats = booked.booking_items.count()
      for seat in booked.booking_items.all():
         session_data['line_items'].append({
            'price_data':{
               'unit_amount':int(seat.show.price * Decimal('100')),
               'currency':'usd',
               'product_data':{
                  'name':f"{seat.show}:{seat.show.start_date}:{seat.show.room.name}:{seat.seat}"
               }
            },
            'quantity':total_seats
         })
      session=stripe.checkout.Session.create(**session_data)
      return redirect(session.url, code=303)
      
   
   return render(request,"process.html")
    
    
def payment_completed(request,booking_id):
   payment_completed_email.delay(booking_id)
   return render(request,"completed.html")


def payment_failed(request):
   return render(request,"failed.html")

def payment_pdf(request,booking_id):
   book=Booking.objects.get(id=booking_id)
   print(book)
   return render(request,"pdf.html",{
      'booking':book
   })

  
    

moviebooking/payments/templates/completed.html
{% extends "base.html" %}
{% block title  %}
payment process
{% endblock  %}

{% block content %}
<div class="auth-container">
    <div class="auth-card">
      <div class="auth-header">
        <h2>Payment Completed</h2>
      </div>
    </div>
  </div>
    
{% endblock  %}

moviebooking/payments/templates/failed.html
{% extends "base.html" %}
{% block title  %}
payment process
{% endblock  %}

{% block content %}
<div class="auth-container">
    <div class="auth-card">
      <div class="auth-header">
        <h2 style="color:red">Payment Failed</h2>
      </div>
    </div>
  </div>
    
{% endblock  %}

moviebooking/payments/templates/pdf.html
{% comment %} <html>
<body>
<h1>Movie</h1>
<p>
Ticket no. {{ booking.booking_code }}<br>
<span class="secondary">
{{ order.created|date:"M d, Y" }}
</span>
</p>
<h3>Ticket for show:</h3>
<div>
    {% with show=booking.get_show %}
    <p>{{ show.movie }}</p>
    <p>{{ show.start_date}}</p>
    <p>{{ show.showtime }}</p>
    <p>{{ show.room.name }}</p>
{% endwith %}

</div>
<p>
    booked by:
{{ booking.name }}<br>
{{ booking.email }}<br>

</p>
{% for seat in booking.booking_items.all  %}
<p>Seat: {{ seat.seat }} </p>

{% endfor %}
Total:{{ booking.get_total_cost }}

</body>
</html> {% endcomment %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ticket</title>
    <link rel="stylesheet" href="{% static "css/pdf.css" %}">
</head>
<body>
    
    <div class="ticket-container">
        <div class="ticket">
          <div class="ticket-header">
            <div class="logo">MovieHub</div>
            <div class="booking-code">
              <span>Booking Code</span>
              <h3>{{booking.booking_code}}</h3>
            </div>
          </div>
          
          <div class="ticket-body">
            {% with show=booking.get_show %}

            <div class="ticket-movie">
              <h2>{{show.movie}}</h2>
              <div class="ticket-info">
                <div class="info-group">
                  <label>Date</label>
                  <p>{{show.start_date}}</p>
                </div>
                <div class="info-group">
                  <label>Time</label>
                  <p>{{show.showtime}}</p>
                </div>
                <div class="info-group">
                  <label>Room</label>
                  <p>{{show.room.name}}</p>
                </div>
              </div>
            </div>
            {% endwith %}
            <div class="ticket-details">
              <div class="info-group">
                <label>Seats</label>
                <p class="seats">
                    {% for seat  in booking.booking_items.all  %}
                    
                   {{seat.seat}}
                    {% endfor %}
                
                </p>
              </div>
              <div class="info-group">
                <label>Price</label>
                <p>{{booking.get_total_cost}}</p>
              </div>
            </div>
            
            {% comment %} <div class="ticket-qr">
              <img src={ticket.qrCode} alt="QR Code" />
              <p class="qr-description">Scan for entry</p>
            </div>
          </div> {% endcomment %}
          
          <div class="ticket-footer">
            <div class="purchase-info">
              <p>Purchased: {{booking.created}}</p>
            </div>
           
          </div>
        </div>
      </div>




</body>
</html>

moviebooking/payments/templates/process.html
{% extends "base.html" %}
{% block title  %}
payment process
{% endblock  %}

{% block content %}
<div class="auth-container">
    <div class="auth-card">
      <div class="auth-header">
        <h2>Complete the payment</h2>
      </div>
      
      
      <form  method="post" action={% url "payment:process" %} class="auth-form">
        <button type="submit" class="auth-button">Pay</button>
        {% csrf_token %}
      </form>
      
    
    </div>
  </div>
    
{% endblock  %}