moviebooking/bookings/urls.py
from django.urls import path
from . import views
urlpatterns = [
 path('<int:id>/<str:movie>',views.book_show,name='book_show'),
path('checkout',views.booking_create,name='checkout')
]

moviebooking/moviebooking/urls.py
from django.contrib import admin
from django.urls import path,include,reverse_lazy
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('Accounts.urls')),
    path('',include('movies.urls')),
    path('booking/',include('bookings.urls')),
    path('tickets/',include('tickets.urls')),
    path('payment/',include('payments.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(
        settings.MEDIA_URL,document_root=settings.MEDIA_ROOT
    )

moviebooking/movies/urls.py
from django.urls import path

from . import views
urlpatterns = [
    path('',views.MovieList,name="movie_list"),
    path('movie/<int:id>',views.MovieDetail,name="movie_detail"),
    path('movie/shows',views.AvailableShows,name='available_shows'),
    path('movie/shows/<str:currentdate>',views.AvailableShows,name='available_shows_withDate'),
    path('movie/bookings',views.movie_bookings,name='see_bookings'),
]

moviebooking/payments/urls.py
from django.urls import path
from . import views
from . import webhooks
app_name='payment'
urlpatterns = [
    path('process/',views.payment_process,name='process'),
    path('completed/<int:booking_id>',views.payment_completed,name='completed'),
    path('failed/',views.payment_failed,name='failed'),
     path('webhook/',webhooks.stripe_webhook,name='stripe-webhook'),
     path('ticket/<int:booking_id>',views.payment_pdf,name='pdf_payment'),
     
   
    

]

moviebooking/bookings/models.py
from django.db import models
from django.core.exceptions import ValidationError
from movies.models import Show,Seat
from django.conf import settings
import time
import random
import uuid


def generate_booking_id():
    timestamp = int(time.time() * 1000) % 100
    
    random_number = random.randint(10, 99)
    
    unique_part = uuid.uuid4().hex[:4]
    
    booking_id = f"{timestamp:02}{random_number}{unique_part}"
    
    return booking_id[:8]


class Booking(models.Model):
    booking_code = models.CharField(max_length=100,default=generate_booking_id())
    name = models.CharField(max_length=300)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)  # Changed to auto_now=True for correct update timestamp
    paid = models.BooleanField(default=False)
    stripe_id=models.CharField(max_length=250,blank=True)
    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name
    
    def get_total_cost(self):
        return sum(item.show.price for item in self.booking_items.all() )
    
    def get_show(self):
        first_item = self.booking_items.first() 
        if first_item:
            return first_item.show  
        return None
    
    def get_stripe_url(self):
        if not self.stripe_id:
            return ''
        if '__test__' in settings.STRIPE_SECRET_KEY:
            path='/test/'
        else:
            path='/'
        return f'https://dashboard.stripe.com{path}payments/{self.stripe_id}'




class BookingSeats(models.Model):
    booking = models.ForeignKey(
        Booking, related_name="booking_items", on_delete=models.CASCADE
    )
    show = models.ForeignKey(
        Show, related_name="booked_seats", on_delete=models.CASCADE,null=True
    )
    seat = models.CharField(max_length=10,null=True)

   

moviebooking/movies/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.urls import reverse
# Create your models here.


class Room(models.Model):
     name=models.CharField(max_length=50)
     seats_row= models.PositiveIntegerField(blank=True)
     num_seats = models.PositiveIntegerField(blank=True)
  





class Movie(models.Model):
    
    class RatingChoices(models.TextChoices):
     G = "G", "G"
     PG = "PG", "PG"
     PG_13 = "PG-13", "PG-13"
     R = "R", "R"
     A = "A", "A"

        
    title=models.CharField(max_length=200)
    genre=TaggableManager()
    description=models.TextField(max_length=500,blank=True)
    posterimage=models.ImageField(
        upload_to="poster/%Y/%m/%d",
        blank=True
    )
    languages=models.JSONField(default=list,blank=True)
    duration=models.TextField(max_length=40, blank=True)
    created=models.DateTimeField(auto_now_add=True,blank=True)
    Rating=models.TextField(
        max_length=6,
        choices=RatingChoices.choices,
        blank=True
    )
    class Meta:
        indexes=[models.Index(fields=['-created'])]
        ordering=['-created']
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('movie_detail',args=[self.id])
    
    
class Show(models.Model):
    movie=models.ForeignKey(Movie,related_name='show_times',on_delete=models.CASCADE)
    start_date = models.DateField(verbose_name="Start Date",null=True)
    price = models.PositiveIntegerField(verbose_name="Ticket Price")
    room=models.ForeignKey(
        Room,
        related_name='running_shows',
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    showtime = models.TimeField(verbose_name="Showtime",auto_now=False, auto_now_add=False,blank=True, null=True)
    class Meta:
        indexes=[models.Index(fields=['-showtime'])]
        ordering=["-start_date"]
    def __str__(self):
     return f"{self.movie.title} - {self.showtime.strftime('%H:%M') if self.showtime else 'No Time'}"
    
    def generate_seats(self):
     total_seats = self.room.num_seats
     num_rows =self.room.seats_row
     
     seatindex = [chr(65 + i) for i in range(num_rows)]  
     
     full_row_size = total_seats // num_rows 
     remaining_seats = total_seats % num_rows 
 
     seats = []  
     
     for i in range(num_rows):
         row_size = full_row_size + (1 if i < remaining_seats else 0)  
         for j in range(1, row_size + 1):
             seats.append(f"{seatindex[i]}{j}")  
  
     Seat.objects.bulk_create([Seat(show=self, seat_num=seat) for seat in seats])
 
    def get_absolute_url(self):
        return reverse("book_show", args=[self.id,self.movie])
    
    def save(self, *args, **kwargs):
     is_new = self.pk is None  # Check if the object is new (unsaved)
     super().save(*args, **kwargs)  # Save the Show first
 
     if is_new and not Seat.objects.filter(show=self).exists():
         self.generate_seats()

    
   
    
    
class Seat(models.Model):
 show=models.ForeignKey(
     Show,
     related_name='seat_num',
     on_delete=models.CASCADE
 )
 seat_num = models.CharField(max_length=25)
 booked=models.BooleanField(default=False)

moviebooking/bookings/forms.py
from django import forms
from .models import Booking

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['name', 'email']  # Only name and email are included

    

moviebooking/bookings/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404,redirect
from django.views.decorators.csrf import csrf_exempt

from movies.models import Seat, Show
from django.urls import reverse
from tickets.ticket import Ticket
from .forms import BookingForm
from django.views.decorators.http import require_POST
from .models import Booking,BookingSeats
import redis
import json

r = redis.Redis()








@csrf_exempt
def book_show(request, id, movie):
    seats = get_list_or_404(
        Seat,
        show=id
    )
    show = get_object_or_404(
        Show,
        id=id
    )
    form=BookingForm()
    if request.user.is_authenticated:
        user = request.user
        initial_data = {'email': user.email, 'name': user.username}
        form=BookingForm(initial_data)
 
    
    
   
    if request.method == "POST":
        ticket=Ticket(request)
        seat_data = json.loads(request.body)
        seat_num = seat_data['seat']  
       
        if seat_data['add']=="True":
            r.set(f"{show.id}:{show.start_date}:{show.room.name}:{seat_num}", seat_num, 360)
            
            seat = get_object_or_404(
                Seat,
                show=show,
                seat_num=seat_num
            )
            seat.booked = True
            seat.save()
            ticket.add(seat)
            
        else:
            r.delete(f"{show.id}:{show.start_date}:{show.room.name}:{seat_num}")
            
            seat = get_object_or_404(
                Seat,
                show=show,
                seat_num=seat_num
            )
            seat.booked = False
            seat.save()
            ticket.remove(seat)
        
        
    
    return render(request, 'booking/Booking.html', {
        'seats': seats,
        'show': show,
        'form':form
    })


@require_POST
def booking_create(request):
    tickets = Ticket(request)
    print(tickets.total())
    
    for show in tickets:
        show_id = show['show_id']
        seats = show['tickets']
        price = show['price']
    
    show = Show.objects.get(id=show_id)
    
    form = BookingForm(request.POST)
    if form.is_valid():
        booked = form.save(commit=False)
        booked.save()
        for seat in seats:
            print(seat)
            BookingSeats.objects.create(
                booking=booked,
                show=show,
                seat=seat
            )
        tickets.clear()
        request.session['booking_id'] = booked.id
        print(booked.id, 'Book')
        
        return redirect('payment:process')
    

 

moviebooking/movies/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Movie,Show
from bookings.models import Booking
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.utils.dateparse import parse_date
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def MovieList(request):
    movies=Movie.objects.all()
    return render(request, "movie/list.html", {
        "route": "home",
        "movies":movies
    })
    
def MovieDetail(request,id):
    movie=get_object_or_404(
        Movie,
        id=id
    )
    print(movie)
    return render(request,"movie/detail.html",{
        "movie":movie
    })
    




@csrf_exempt
def AvailableShows(request, currentdate=None):
    if currentdate:
        currentdate = parse_date(currentdate)  
    else:
        currentdate = datetime.date.today()  

    shows = Movie.objects.filter(
        show_times__isnull=False,
        show_times__start_date__lte=currentdate,
        
    ).distinct()
   
    
    if not shows.exists():
        shows=None
    if request.method=='POST':
        print(request.body)

    return render(request, 'shows/list.html', {
        'shows': shows,
        'currentdate': currentdate.isoformat()
    })
    




def movie_bookings(request):
    booking = None
    error_message = None
    seats = []
    mybookings=[]
    if request.user.is_authenticated:
        user_email=request.user.email
        print(user_email)
        mybookings=Booking.objects.filter(email=user_email)
        
    
    
    if request.method == 'POST':
        cd = request.POST
        booking_code = cd.get('bookingcode')

        if booking_code:
            try:
                # Fetch the booking object based on the booking code
                booking = Booking.objects.get(booking_code=booking_code)
                # Fetch related seat data (adjust based on your actual model relationships)
                seats = booking.booking_items.all()
            except Booking.DoesNotExist:
                error_message = "No booking found with the provided booking code"
        else:
            error_message = "Please enter a booking code"

    if seats:
        first_show = seats[0].show  
    else:
        first_show = None  

    return render(request, 'shows/bookings.html', {
        'booking': booking,
        'seats': seats, 
        'error_message': error_message,
        'mybookings':mybookings
    })





    

moviebooking/movies/templates/shows/bookings.html
{% extends "base.html" %}
{% block title %}
booking
{% endblock  %}

{% block content %}
<div class="booking-search">
<form method="post">
<input type="text" name="bookingcode" placeholder="Enter your booking code"/>
<input type="submit" value="Search" class="browse-btn"/>
{% csrf_token %}

</form>
</div>

{% if booking  %}

{% with show=booking.get_show %}
  <div class="booking-list">
    <div class="booking-card" key={{ booking.id }}>
      <div class="booking-poster">
        <img src="{{ show.movie.posterimage.url }}" alt="{{ show.movie }}" />
      </div>
      <div class="booking-details">
        <h3>{{ show.movie }}</h3>
        <div class="booking-meta">
          <div class="booking-date-time">
            <p><strong>Date:</strong> {{ show.start_date }}</p>
            <p><strong>Time:</strong> {{ show.showtime }}</p>
          </div>
          <div class="booking-tickets">
            <p><strong>Booking code:</strong> {{ booking.booking_code }}</p>
            <p><strong>Seats:</strong> 
                {% for seat in booking.booking_items.all  %}
               {{ seat.seat }}
            {% endfor %}
            </p>
          </div>
          <div class="booking-total">
            <p><strong>Total:</strong> ${{ booking.get_total_cost }}</p>
          </div>
        </div>
        <div class="booking-actions">
          <a class="view-ticket-btn" >View Ticket</a>
        </div>
      </div>
    </div>
  </div>
  {% endwith %}

{% endif %}

{% if error_message %}
{{error_message}}
{% endif %}




{% if request.user.is_authenticated  %}
<div class="booking-history">
    <h2>Booking History</h2>
    
  {% if mybookings %}
  {% for booking in mybookings %}
  {% with show=booking.get_show %}
  <div class="booking-list">
    <div class="booking-card" key={{ booking.id }}>
      <div class="booking-poster">
        <img src="{{ show.movie.posterimage.url }}" alt="{{ show.movie }}" />
      </div>
      <div class="booking-details">
        <h3>{{ show.movie }}</h3>
        <div class="booking-meta">
          <div class="booking-date-time">
            <p><strong>Date:</strong> {{ show.start_date }}</p>
            <p><strong>Time:</strong> {{ show.showtime }}</p>
          </div>
          <div class="booking-tickets">
            <p><strong>Booking code:</strong> {{ booking.booking_code }}</p>
            <p><strong>Seats:</strong> 
                {% for seat in booking.booking_items.all  %}
               {{ seat.seat }}
            {% endfor %}
            </p>
          </div>
          <div class="booking-total">
            <p><strong>Total:</strong> ${{ booking.get_total_cost }}</p>
          </div>
        </div>
        <div class="booking-actions">
          <a class="view-ticket-btn" href="{% url 'payment:pdf_payment' booking.id %}">View Ticket</a>

        </div>
      </div>
    </div>
  </div>
  {% endwith %}
{% endfor %}

{% else %}



      <div class="no-bookings">
        <p>You haven't made any bookings yet.</p>
        <a href="{% url "available_shows"%}" class="browse-btn">Browse Movies</a>
      </div>
  
   

      {% endif %}

  </div>

  {% endif %}

{% endblock  %}

moviebooking/movies/templates/shows/list.html
{% extends "base.html" %}
{% block title %}
Bookmyticket
{% endblock  %}
{% block  content%}
<div>
  Select a Date:<input type="date" value="{{currentdate}}" id="show-date-picker"/>
</div>

  <section class="shows-section">
    <h1>
      {% if shows %}
  
      All Shows
      {% else %}
      No Shows on this date
      {% endif %}
    
    </h1>
    <div class="shows-container">
{% for show  in shows  %}
 
    <div class="show-item">
      <div class="show-poster">
        <img src={{show.posterimage.url}} alt="MOVIE_TITLE" />
      </div>
      <div class="show-details">
        <h2>{{show.title}}</h2>
        <div class="movie-info-column">
          <p><strong>Genre:</strong> {{show.genre.all|join:", "}}</p>
          <p><strong>Rating:</strong> {{show.Rating}}</p>
          <p><strong>Duration:</strong> {{show.duration}}</p>
        </div>
        <h3>Showtimes:</h3>
        <div class="showtimes-grid">
          {% for s in show.show_times.all  %}
          <div class="showtime-card">
            <p class="showtime-date">{{currentdate}}</p>
            <p class="showtime-time">{{s.showtime}}</p>
            <p class="showtime-price">Rs{{s.price}}</p>
            <a href={{s.get_absolute_url}}  class="book-btn">Book</a>
          </div>
          {% endfor %}
        </div>
        <a href={{show.get_absolute_url}} class="detail-btn">View Details</a>
      </div>
    </div>
 



  {% endfor %}
</div>
</section>

{% endblock  %}
{% block domready %}


let datetime=document.getElementById('show-date-picker')

 datetime.addEventListener("change", function(event) {
  let selectedDate = event.target.value;
  if(selectedDate){
  let baseUrl  = `${window.location.origin}/movie/shows/${selectedDate}`;
window.location.href=baseUrl
  }
}); 


{% endblock  %}